### ISSUE TITLE
Update the whole list of first phase results

### ISSUE THREAD

**Issue by nikeshbalami** [okfnepal/election-nepal-data#12]
Scrap and update result list: http://result.election.gov.np/ElectionResultDetails.aspx

**Comment by amitness** [comment]
https://drive.google.com/file/d/0B1H_7a3Y_qOMa2xJU0wzQkdrT1U/view?usp=sharing

**Comment by nikeshbalami** [comment]
Thank You Amit for this, Previously I tried that but it was throwing the fonts errors. Yours looks perfect, currently I am categorizing the result over here https://github.com/okfnepal/election-nepal-data/tree/master/results/स्थानीय%20चुनावको%20परिणाम. This will help me so much, will update everything ASAP.

**Comment by nikeshbalami** [comment]
Solved by #15
