### ISSUE TITLE
Organize the data into folders

### ISSUE THREAD

**Issue by amitness** [okfnepal/election-nepal-data#5]
As the number of datasets increase, it'll be helpful to make separate folders to keep it organized. This will break the links on the site, so we need to make change to links of current data on the site parallely.

Here's the folders I propose:
```
- Geography: Any data related to geo: `districts, ward, federal structures`
- Demographics: Any numeric data: population count, ...
- Expenditure: Cost
```

**Comment by nikeshbalami** [comment]
This is great @studenton, I will work on it
