### ISSUE TITLE
Clean dataset: Remove commas from numeric data in dataset

### ISSUE THREAD

**Issue by amitness** [okfnepal/election-nepal-data#8]
Convert ```1,000``` => `1000`

Advantage:
- It'll be easier to read that data in Python or any language without needing to format `1,000` to `1000`.

- When CSV is rendered in some programs, they mistake comma inside the number as separate column and you get error like this. An example being: http://datapipes.okfnlabs.org/html/ is rendering wrong tables for our data.

Actual data: `1000,"2,000"` (2 columns) is interpreted as:

Rendered data: `1000, 2, 000` (3 columns)

**Comment by nikeshbalami** [comment]
hehe I was bored and lazy cleaning those things :p, Will do it from onwards

**Comment by amitness** [comment]
Sure. I'll do the existing ones.

**Comment by amitness** [comment]
Done for existing data.
